config/routes.rb
Bigmouth::Engine.routes.draw do
  get "admin" => redirect("admin/articles")
  resources :articles, only: %i(index show), path: ""
  root "articles#index"

  namespace :admin do
    resources :articles
    resources :images
    root "articles#index"
  end
end

app/models/bigmouth/article.rb
module Bigmouth
  class Article < ActiveRecord::Base
    belongs_to :user, class_name: Bigmouth.config.user_class
    validates :title, presence: true

    default_scope { order created_at: :desc }
  end
end

app/models/bigmouth/file.rb
module Bigmouth
  class File < ActiveRecord::Base
    belongs_to :user, class_name: Bigmouth.config.user_class
  end
end

app/models/bigmouth/image.rb
module Bigmouth
  class Image < ActiveRecord::Base
    belongs_to :user, class_name: Bigmouth.config.user_class

    attachment :image_file, type: :image

    default_scope { order created_at: :desc }
  end
end

app/controllers/bigmouth/admin/application_controller.rb
class Bigmouth::Admin::ApplicationController < ApplicationController
  def action_requires_login
    if current_user.blank?
      redirect_back_or_to Bigmouth.config.sign_in_uri[:uri],
                          alert: "You are not permitted to do this action."
    end
  end
end

app/controllers/bigmouth/admin/articles_controller.rb
require_dependency "bigmouth/application_controller"

module Bigmouth
  class Admin::ArticlesController < Admin::ApplicationController

    layout "bigmouth/admin/dashboard"

    before_action :set_article, only: %i(show edit update destroy)
    before_action :action_requires_login

    def index
      @articles = Article.all
    end

    def show
    end

    def new
      @article = Article.new
    end

    def edit
    end

    def create
      @article = Article.new(article_params)
      @article.user_id = current_user.id

      if @article.save
        redirect_to admin_article_path(@article), notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    def update
      if @article.update(article_params)
        redirect_to admin_article_path(@article), notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy
      redirect_to admin_articles_url, notice: 'Article was successfully destroyed.'
    end

    private
      # Only allow a trusted parameter "white list" through.
      def article_params
        params.require(:article).permit(:title, :text)
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params[:id])
      end
  end
end

app/controllers/bigmouth/admin/images_controller.rb
require_dependency "bigmouth/application_controller"

module Bigmouth
  class Admin::ImagesController < Admin::ApplicationController

    layout "bigmouth/admin/dashboard"

    before_action :set_image, only: %i(show edit update destroy)
    before_action :action_requires_login

    def index
      @images = Bigmouth::Image.all
    end

    def show
    end

    def new
      @image = Bigmouth::Image.new
    end

    def edit
    end

    def create
      @image = Bigmouth::Image.new(image_params)
      @image.user_id = current_user.id

      if @image.save
        redirect_to admin_image_path(@image), notice: 'Image was successfully created.'
      else
        render :new
      end
    end

    def update
      if @image.update(image_params)
        redirect_to admin_image_path(@image), notice: 'Image was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @image.destroy
      redirect_to admin_images_url, notice: 'Image was successfully destroyed.'
    end

    private
      # Only allow a trusted parameter "white list" through.
      def image_params
        params.require(:image).permit(:label, :image_file)
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_image
        @image = Bigmouth::Image.find(params[:id])
      end
  end
end

app/controllers/bigmouth/application_controller.rb
class Bigmouth::ApplicationController < ApplicationController
end

app/controllers/bigmouth/articles_controller.rb
require_dependency "bigmouth/application_controller"

module Bigmouth
  class ArticlesController < ApplicationController

    layout "bigmouth/default"

    before_action :set_article, only: %i(show)

    # GET /articles
    def index
      @articles = Article.all
      render :index, layout: Bigmouth.config.layout
    end

    # GET /articles/1
    def show
      render :show, layout: Bigmouth.config.layout
    end

    private

      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params[:id])
      end
  end
end

app/helpers/bigmouth/admin/application_helper.rb
module Bigmouth
  module Admin::ApplicationHelper

    include Bigmouth::ApplicationHelper

    def uploaded_by(image)
      if image.user.present?
        image.user[Bigmouth.config.username_key.to_sym] || "Guest"
      else
        "Guest"
      end
    end

    def sidebar_activate(sidebar_link_url)
      current_url = request.headers["SCRIPT_NAME"] + request.headers["PATH_INFO"]
      current_url.match(sidebar_link_url) ? ' class="active"' : ""
    end

    def sidebar_list_items
      items = [
        { text: "Articles", path: admin_articles_path },
        { text: "Images", path: admin_images_path }
      ]

      html = ""
      items.each do |item|
        text = item[:text]
        path = item[:path]
        html += %(<li#{sidebar_activate(path)}><a href="#{path}">#{text}</a></li>)
      end

      html.html_safe
    end
  end
end

app/helpers/bigmouth/application_helper.rb
module Bigmouth
  module ApplicationHelper
    # Returns Bootstrap friendly type
    def alert_class_for(flash_type)
      {
        success: 'alert-success',
        error: 'alert-danger',
        danger: 'alert-danger',
        alert: 'alert-warning',
        notice: 'alert-info'
      }[flash_type.to_sym] || flash_type.to_s
    end

    def author(article)
      if article.user.present?
        article.user[Bigmouth.config.username_key.to_sym] || "Guest"
      else
        "Guest"
      end
    end

    def summary(article)
      truncate_html sanitize(article.text),
                    length: Bigmouth.config.summary_length,
                    omission: "..."
    end
  end
end

app/views/bigmouth/admin/articles/_form.html.slim
= form_for [:admin, @article] do |f|
  - if @article.errors.any?
    #error_explanation
      h2
        = pluralize(@article.errors.count, "error")
        |  prohibited this article from being saved:
      ul
        - @article.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :text
    = f.text_area :text, class: ["tinymce", "form-control"], rows: 40, cols: 120
    = tinymce
  .actions
    = f.submit "Submit", class: ["btn", "btn-default"]

app/views/bigmouth/admin/articles/edit.html.slim
h1
  | Editing Article
= render 'form'
= link_to 'Preview', admin_article_path(@article), target: ["_blank"]
|  | 
= link_to 'Back', admin_articles_path

app/views/bigmouth/admin/articles/index.html.slim
- provide(:title, "Articles (admin)")
h1
  | Articles
.table-responsive
  table.table.table-striped
    thead
      tr
        th Title
        th Created at
        th colspan="3"
    tbody
      - @articles.each do |article|
        tr
          td
            = link_to article.title, article
          td
            = article.created_at.strftime(Bigmouth.config.datetime_format)
          td
            = link_to "Show", article
          td
            = link_to "Preview", admin_article_path(article), target: ["_blank"]
          td
            = link_to "Edit", edit_admin_article_path(article), class: "btn btn-primary btn-xs"
          td
            = link_to "Destroy", admin_article_path(article), method: :delete, data: { confirm: "Are you absolutely sure you want to delete <strong>#{article.title}</strong>?",
                                                                                       "verify" => article.title,
                                                                                       "verify-text" => " This action cannot be undone. Please type in the name of the article to confirm.",
                                                                                       }, title: "Verify the deletion", class: "btn btn-danger btn-xs"
= link_to 'New Article', new_admin_article_path, class: "btn btn-default"

app/views/bigmouth/admin/articles/new.html.slim
h1
  | New Article
= render 'form'
= link_to 'Back', admin_articles_path

app/views/bigmouth/admin/articles/show.html.slim
p
  = link_to '<< Back', admin_articles_path, class: "btn btn-default"
p
  = link_to 'Edit', edit_admin_article_path(@article), class: "btn btn-primary"
h1.article-title
  = @article.title
p.lead.article-author
  | by 
  = author @article
hr
p.posted-date
  span.glyphicon.glyphicon-time
  |  Posted on 
  = @article.created_at.strftime(Bigmouth.config.datetime_format)
hr
.article-body
  = sanitize @article.text

app/views/bigmouth/admin/images/_form.html.slim
= form_for [:admin, @image] do |f|
  - if @image.errors.any?
    #error_explanation
      h2
        = pluralize(@image.errors.count, "error")
        |  prohibited this image from being saved:
      ul
        - @image.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :label
    = f.text_field :label, class: "form-control"
  .form-group
    = f.label :image_file
    = f.attachment_field :image_file
  .actions
    = f.submit "Submit", class: ["btn", "btn-default"]

app/views/bigmouth/admin/images/edit.html.slim
h1
  | Editing Image
= render 'form'
= link_to 'Preview', admin_image_path(@image), target: ["_blank"]
|  | 
= link_to 'Back', admin_images_path

app/views/bigmouth/admin/images/index.html.slim
- provide(:title, "Images (admin)")
.table-responsive
  table.table.table-striped
    thead
      tr
        th Image
        th Label
        th Created at
        th colspan="2"
    tbody
      - @images.each do |image|
        tr
          td
            = image_tag attachment_url(image, :image_file, :fill, 50, 50)
          td
            = link_to image.label, admin_image_path(image)
          td
            = image.created_at.strftime(Bigmouth.config.datetime_format)
          td
            = link_to "Show", admin_image_path(image)
          td
            = link_to "Edit", edit_admin_image_path(image), class: "btn btn-primary btn-xs"
          td
            = link_to "Destroy", admin_image_path(image), method: :delete, data: { confirm: "Are you absolutely sure you want to delete <strong>#{image.label}</strong>?",
                                                                                       "verify" => image.label,
                                                                                       "verify-text" => " This action cannot be undone. Please type in the name of the image to confirm.",
                                                                                       }, label: "Verify the deletion", class: "btn btn-danger btn-xs"
= link_to 'New Image', new_admin_image_path, class: "btn btn-default"

app/views/bigmouth/admin/images/new.html.slim
h1
  | New Image
= render 'form'
= link_to 'Back', admin_images_path

app/views/bigmouth/admin/images/show.html.slim
h1.image-label
  = @image.label
p.lead.image-uploaded-by
  | by 
  = uploaded_by @image
hr
h3
  | Image URL
p
  = attachment_url(@image, :image_file, filename: @image.label)
p
  // = image_tag attachment_url(@image, :image_file, :fill, 600, 600)
  = image_tag attachment_url(@image, :image_file)
hr
= link_to 'Edit', edit_admin_image_path(@image)
|  | 
= link_to 'Back', admin_images_path

app/views/bigmouth/articles/index.html.slim
.articles
  - @articles.each do |article|
    .article
      h1.article-title
        = link_to article.title, article
      p.lead.article-author
        | by 
        = author article
      hr
      p.posted-date
        span.glyphicon.glyphicon-time
        |  Posted on 
        = article.created_at.strftime(Bigmouth.config.datetime_format)
      hr
      .article-body
        = summary(article)
      .read-more
        = link_to "Read More >>", article
      hr

app/views/bigmouth/articles/show.html.slim
h1.article-title
  = @article.title
p.lead.article-author
  | by 
  = author @article
hr
p.posted-date
  span.glyphicon.glyphicon-time
  |  Posted on 
  = @article.created_at.strftime(Bigmouth.config.datetime_format)
hr
.article-body
  = sanitize @article.text
= link_to 'Back', articles_path

app/views/layouts/bigmouth/admin/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      = "#{yield(:title)} | Bigmouth Admin"
    = stylesheet_link_tag    "bigmouth/admin/dashboard", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "bigmouth/admin/dashboard", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top role="navigation"
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Bigmouth Admin", admin_root_path, class: "navbar-brand"
        p.navbar-text.navbar-left
          = link_to "Back to Articles", admin_root_path, class: "navbar-link"
        p.navbar-text.navbar-right
           = "Logged in as: #{current_user ? current_user[Bigmouth.config.username_key.to_sym] : 'Guest'}"
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          ul.nav.nav-sidebar
            = sidebar_list_items()
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          .flash
            - flash.each do |message_type, message|
              .alert class="#{alert_class_for(message_type)}"
                = message
          = yield

app/views/layouts/bigmouth/admin/dashboard.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      = "#{yield(:title)} | Bigmouth Admin"
    = stylesheet_link_tag    "bigmouth/admin/dashboard", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "bigmouth/admin/dashboard", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top role="navigation"
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed type="button" aria-controls="navbar" data-target="#navbar-fuck" data-toggle="collapse"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Bigmouth Admin", admin_root_path, class: "navbar-brand"
        #navbar-fuck.navbar-collapse.collapse
          ul#navbar-list-menu.nav.navbar-nav
            = sidebar_list_items()
          ul.nav.navbar-nav.navbar-right
            li.dropdown
              a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                = current_user ? current_user[Bigmouth.config.username_key.to_sym] : "Guest"
                span.caret
              ul.dropdown-menu role="menu"
                li
                  a href="#"
                    | Action
                li
                  a href="#"
                    | Another Action
                li
                  a href="#"
                    | Something else here
                li.divider
                li
                  a href="#"
                  = link_to "Sign out", Bigmouth.config.sign_out_uri[:uri], method: Bigmouth.config.sign_out_uri[:method]
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          ul.nav.nav-sidebar
            = sidebar_list_items()
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          .flash
            - flash.each do |message_type, message|
              .alert class="#{alert_class_for(message_type)}"
                = message
          = yield

app/views/layouts/bigmouth/default.html.slim
doctype html
html
  head
    title
      | Bigmouth
    = stylesheet_link_tag    "bigmouth/application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "bigmouth/application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          - if controller.action_name == 'new' || controller.action_name == "edit"
            = link_to "Bigmouth Editor", "#", class: "navbar-brand"
          - else
            = link_to "Bigmouth", "#", class: "navbar-brand"
        p.navbar-text.navbar-left
          = link_to "Back to Articles", root_path, class: "navbar-link"
        p.navbar-text.navbar-right
           = "Logged in as: #{current_user ? current_user[Bigmouth.config.username_key.to_sym] : 'Guest'}"
    .container
      .flash
        - flash.each do |message_type, message|
          .alert class="#{alert_class_for(message_type)}"
            = message
      = yield